// swift-tools-version: 5.5

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Taps",
    platforms: [
        .iOS("15.2")
    ],
    products: [
        .iOSApplication(
            name: "Taps",
            targets: ["AppModule"],
            bundleIdentifier: "io.github.mfahmialkautsar.Taps",
            teamIdentifier: "BAFJ582D2S",
            displayVersion: "1.0",
            bundleVersion: "1",
            iconAssetName: "AppIcon",
            accentColorAssetName: "AccentColor",
            supportedDeviceFamilies: [
                .pad,
            ],
            supportedInterfaceOrientations: [
                .portrait,
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: "."
        )
    ]
)
